# -*- coding: utf-8 -*-
"""Building Language Detection Model with Naive Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1css97075tias0WOEUWL1HGwrLEXGu9L2
"""

!pip install -U scikit-learn

import pandas as pd
from google.colab import files
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import train_test_split

uplooad = files.upload()

data = pd.read_csv('Language Detection.csv')

data.head()

x = data["Text"]
y = data["Language"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = make_pipeline(TfidfVectorizer(),MultinomialNB())
model.fit(X_train, y_train)
print("The model accuracy is : ",model.score(X_test, y_test))
def detect_language(text):
    detected_language = model.predict([text])[0]
    return detected_language

if __name__ == "__main__":
  while True:
    input_text = input("Enter a text: ")
    if input_text.lower() == 'exit':
      print("Exiting The Language Detection System")
      break
    detected_language = detect_language(input_text)
    print(f"The language of the input text is: {detected_language}")